### PR TITLE
Fixes for two Django deprecated warnings

### PR DESCRIPTION
**Pull request by shushen**
With `PYTHONWARNINGS=default::DeprecationWarning` environment variable set, there are a couple `deprecated` warnings thrown when running `pytest`.

This PR fixes these warnings.

### CODE REVIEW

**Comment by melinath** [comment]
I'm not seeing the deprecation warnings; what version of Django are you using?

**Comment by melinath** [comment]
(@shushen)

**Comment by shushen** [comment]
Django version is per `requirements.txt`: `Django==1.11.4`, and the warnings are shown if the environment variable `PYTHONWARNINGS=default::DeprecationWarning` is set when running `pytest`. For example,

```
$ PYTHONWARNINGS=default::DeprecationWarning pytest .
```

**Comment by melinath** [comment]
Right, you totally said that. Thanks!

**Pull request merged**
